name: Release Please

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: smartparking
  release:
    runs-on: ubuntu-latest
    needs: release_please
    if: ${{ needs.release_please.outputs.release_created }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Copy MAPS_API_KEY
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: echo MAPS_API_KEY=\"$MAPS_API_KEY\" > ./local.properties
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # Publish docs
      - name: Build release docs
        run: ./gradlew dokkaHtmlMultiModule
      - name: Setup Github Pages
        uses: actions/configure-pages@v3
      - name: Upload release docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/dokka/htmlMultiModule'
      - name: Deploy release docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      # Generate and upload jar
      - name: Bump version code
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}
      - name: Build app
        run: ./gradlew assembleRelease
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.release_please.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Upload PROD app to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS_FILE_CONTENT }}
          groups: prod
          file: app/build/outputs/apk/release/app-release-unsigned.apk
